disallowed-types = [
    "std::collections::HashMap",
    "std::collections::HashSet",
]

enforced-import-renames = [
    { path = "ahash::AHashMap", rename = "HashMap" },
    { path = "ahash::AHashSet", rename = "HashSet" },
]
