blank_lines_upper_bound = 2

comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true

condense_wildcard_suffixes = true
reorder_impl_items = true
format_strings = true

group_imports = "StdExternalCrate"
imports_granularity = "Module"
